config/routes.rb
Rails.application.routes.draw do
  resources :ideas do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "ideas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  broadcasts_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title
  has_rich_text :description
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_idea

  def create
    comment = @idea.comments.create! params.required(:comment).permit(:content)
    CommentsMailer.submitted(comment).deliver_later
    redirect_to @idea
  end

  private
  def set_idea
    @idea = Idea.find(params[:idea_id])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: %i[ show edit update destroy ]

  # GET /ideas or /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1 or /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas or /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <%=-comment.content %>
  - <%= time_tag comment.created_at, "data-local": "time-ago" %>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ idea, Comment.new ] do |form| %>
  Your comment: <br>
  <%= form.text_area :content, size: "15x5" %><br>
  <%= form.submit %>
<% end %>

app/views/ideas/_comments.html.erb
<h2>Comments</h2>

<div id="comments">
  <%= render idea.comments %>
</div>

<%= render "comments/new" , idea: idea %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>">
  <p>
    <strong>Title:</strong>
    <%= idea.title %>
  </p>

  <p>Thought of <%= time_tag idea.created_at, "data-local": "time-ago" %></p>

  <p>
    <strong><%= pluralize idea.comments.count, "comment" %></strong>
  </p>

  <p>
    <strong>Description:</strong>
    <%= idea.description %>
  </p>

</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ideas</h1>

<div id="ideas">
  <% @ideas.each do |idea| %>
    <%= render idea %>
    <p>
      <%= link_to "Show this idea", idea %>
    </p>
  <% end %>
</div>

<%= link_to "New idea", new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/show.html.erb
<%= turbo_stream_from @idea %>

<p style="color: green"><%= notice %></p>

<%= render @idea %>
<%= render "ideas/comments", idea: @idea %>

<div>
  <%= link_to "Edit this idea", edit_idea_path(@idea) %> |
  <%= link_to "Back to ideas", ideas_path %>

  <%= button_to "Destroy this idea", @idea, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideaforxyz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>